# @package _global_

defaults:
  - override /data: dexjoco_water_plant
  - override /model: fastwam
  - _self_

batch_size: 8
num_workers: 4

model:
  mot_checkpoint_mixed_attn: false
  proprio_dim: null
  state_dit_config: null

lr_scheduler_type: "cosine"
learning_rate: 1e-4
num_epochs: 5
max_steps: null
log_every: 10
save_every: 500
eval_every: 500

gradient_accumulation_steps: 1
weight_decay: 1e-2
resume: null

wandb:
  enabled: true
  workspace: null
  project: fast-wam
  name: dexjoco_water_plant_uncond_1cam_384_1e-4
  group: dexjoco_water_plant
  mode: online
