# @package _global_

defaults:
  - override /data: water_plant_state_line_probe_2cam
  - override /model: fastwam
  - _self_

batch_size: 4
num_workers: 4

model:
  mot_checkpoint_mixed_attn: false

lr_scheduler_type: cosine
learning_rate: 1e-4
num_epochs: 5
max_steps: null
log_every: 10
save_every: 500
eval_every: 500

gradient_accumulation_steps: 1
weight_decay: 1e-2
resume: null

wandb:
  enabled: true
  workspace: null
  project: fitwam
  name: water_plant_state_line_probe_uncond_2cam_384_1e-4
  group: water_plant_state_line_probe
  mode: online
